In [40]:
import numpy as np
import pandas as pd

In [41]:
df = pd.read_csv("SMUsers.csv")

In [42]:
df

UserID                Name  Gender         DOB  \
0           1       Jesse Lawhorn  Female  1958-10-15   
1           2         Stacy Payne  Female  2004-07-21   
2           3  Katrina Nicewander  Female  2000-02-07   
3           4      Eric Yarbrough    Male  1985-04-14   
4           5       Daniel Adkins  Female  1955-09-18   
...       ...                 ...     ...         ...   
99995   99996      Lionel Denault  Female  1983-07-31   
99996   99997     Margie Mieszala  Female  1954-05-20   
99997   99998       Joan Mercedes    Male  1975-06-06   
99998   99999        Marvin Massa  Female  1959-11-16   
99999  100000          Josh Young  Female  1988-07-29   

                                               Interests  \
0                'Movies', 'Fashion', 'Fashion', 'Books'   
1      'Gaming', 'Finance and investments', 'Outdoor ...   
2        'DIY and crafts', 'Music', 'Science', 'Fashion'   
3           'Outdoor activities', 'Cars and automobiles'   
4                                  'Politics', 'History'   
...                                                  ...   
99995                                   'DIY and crafts'   
99996  'Cars and automobiles', 'Cooking', 'Outdoor ac...   
99997         'Business and entrepreneurship', 'Cooking'   
99998  'Gaming', 'Business and entrepreneurship', 'Fa...   
99999                                 'Politics', 'Pets'   

                       City    Country  
0                   Sibolga  Indonesia  
1                  Al Abyār      Libya  
2               Wādī as Sīr     Jordan  
3                    Matera      Italy  
4                   Biruaca  Venezuela  
...                     ...        ...  
99995                 Dawan      China  
99996  Arcos de la Frontera      Spain  
99997             Los Andes      Chile  
99998               Varjota     Brazil  
99999                 Brzeg     Poland  

[100000 rows x 7 columns]

In [43]:
df['DOB'] = pd.to_datetime(df['DOB'])
today = pd.to_datetime('today')
df['Age'] = round((today-df['DOB']).dt.days/365).astype(int)

In [44]:
df['Age']

0        67
1        21
2        25
3        40
4        70
         ..
99995    42
99996    71
99997    50
99998    65
99999    37
Name: Age, Length: 100000, dtype: int64

In [45]:
df

UserID                Name  Gender        DOB  \
0           1       Jesse Lawhorn  Female 1958-10-15   
1           2         Stacy Payne  Female 2004-07-21   
2           3  Katrina Nicewander  Female 2000-02-07   
3           4      Eric Yarbrough    Male 1985-04-14   
4           5       Daniel Adkins  Female 1955-09-18   
...       ...                 ...     ...        ...   
99995   99996      Lionel Denault  Female 1983-07-31   
99996   99997     Margie Mieszala  Female 1954-05-20   
99997   99998       Joan Mercedes    Male 1975-06-06   
99998   99999        Marvin Massa  Female 1959-11-16   
99999  100000          Josh Young  Female 1988-07-29   

                                               Interests  \
0                'Movies', 'Fashion', 'Fashion', 'Books'   
1      'Gaming', 'Finance and investments', 'Outdoor ...   
2        'DIY and crafts', 'Music', 'Science', 'Fashion'   
3           'Outdoor activities', 'Cars and automobiles'   
4                                  'Politics', 'History'   
...                                                  ...   
99995                                   'DIY and crafts'   
99996  'Cars and automobiles', 'Cooking', 'Outdoor ac...   
99997         'Business and entrepreneurship', 'Cooking'   
99998  'Gaming', 'Business and entrepreneurship', 'Fa...   
99999                                 'Politics', 'Pets'   

                       City    Country  Age  
0                   Sibolga  Indonesia   67  
1                  Al Abyār      Libya   21  
2               Wādī as Sīr     Jordan   25  
3                    Matera      Italy   40  
4                   Biruaca  Venezuela   70  
...                     ...        ...  ...  
99995                 Dawan      China   42  
99996  Arcos de la Frontera      Spain   71  
99997             Los Andes      Chile   50  
99998               Varjota     Brazil   65  
99999                 Brzeg     Poland   37  

[100000 rows x 8 columns]

In [46]:
df.drop(df[df['Country'] != 'India'].index, inplace = True)

In [47]:
df.drop(columns=['DOB'], inplace=True)

In [48]:
df

UserID               Name  Gender  \
9          10   Charles Figueroa  Female   
14         15      Homer Maxwell    Male   
15         16       Frank Holmes  Female   
21         22  Bobby Christensen    Male   
35         36        Erica Dilks  Female   
...       ...                ...     ...   
99936   99937      David Burgess  Female   
99952   99953     Jacquelin Cook    Male   
99975   99976      Katie Almeida    Male   
99977   99978       George Macon    Male   
99987   99988       Shannon Veal  Female   

                                               Interests          City  \
9                                            'Gardening'        Ongole   
14     'Art', 'Cooking', 'Cars and automobiles', 'Fas...        Biaora   
15                             'Music', 'Pets', 'Sports'    Islāmnagar   
21                                      'Nature', 'Pets'      Rājpīpla   
35                                 'Health and wellness'  Quthbullapur   
...                                                  ...           ...   
99936                               'History', 'Fashion'      Kākināda   
99952              'Nature', 'Fashion', 'Fashion', 'Art'        Multai   
99975                'DIY and crafts', 'Movies', 'Books'        Pehowa   
99977                                          'History'    Shertallai   
99987  'Cooking', 'Business and entrepreneurship', 'O...     Amaravati   

      Country  Age  
9       India   22  
14      India   56  
15      India   41  
21      India   59  
35      India   32  
...       ...  ...  
99936   India   62  
99952   India   48  
99975   India   38  
99977   India   29  
99987   India   55  

[9399 rows x 7 columns]

In [49]:
df['Interests'] = df['Interests'].str.split(", ").apply(lambda x: [i.strip("'") for i in x])

In [50]:
df

UserID               Name  Gender  \
9          10   Charles Figueroa  Female   
14         15      Homer Maxwell    Male   
15         16       Frank Holmes  Female   
21         22  Bobby Christensen    Male   
35         36        Erica Dilks  Female   
...       ...                ...     ...   
99936   99937      David Burgess  Female   
99952   99953     Jacquelin Cook    Male   
99975   99976      Katie Almeida    Male   
99977   99978       George Macon    Male   
99987   99988       Shannon Veal  Female   

                                               Interests          City  \
9                                            [Gardening]        Ongole   
14     [Art, Cooking, Cars and automobiles, Fashion, ...        Biaora   
15                                 [Music, Pets, Sports]    Islāmnagar   
21                                        [Nature, Pets]      Rājpīpla   
35                                 [Health and wellness]  Quthbullapur   
...                                                  ...           ...   
99936                                 [History, Fashion]      Kākināda   
99952                    [Nature, Fashion, Fashion, Art]        Multai   
99975                    [DIY and crafts, Movies, Books]        Pehowa   
99977                                          [History]    Shertallai   
99987  [Cooking, Business and entrepreneurship, Outdo...     Amaravati   

      Country  Age  
9       India   22  
14      India   56  
15      India   41  
21      India   59  
35      India   32  
...       ...  ...  
99936   India   62  
99952   India   48  
99975   India   38  
99977   India   29  
99987   India   55  

[9399 rows x 7 columns]

In [51]:
df['Interests'] = df['Interests'].apply(lambda x:[i.replace(" ", "") for i in x])

In [52]:
df

UserID               Name  Gender  \
9          10   Charles Figueroa  Female   
14         15      Homer Maxwell    Male   
15         16       Frank Holmes  Female   
21         22  Bobby Christensen    Male   
35         36        Erica Dilks  Female   
...       ...                ...     ...   
99936   99937      David Burgess  Female   
99952   99953     Jacquelin Cook    Male   
99975   99976      Katie Almeida    Male   
99977   99978       George Macon    Male   
99987   99988       Shannon Veal  Female   

                                               Interests          City  \
9                                            [Gardening]        Ongole   
14     [Art, Cooking, Carsandautomobiles, Fashion, Hi...        Biaora   
15                                 [Music, Pets, Sports]    Islāmnagar   
21                                        [Nature, Pets]      Rājpīpla   
35                                   [Healthandwellness]  Quthbullapur   
...                                                  ...           ...   
99936                                 [History, Fashion]      Kākināda   
99952                    [Nature, Fashion, Fashion, Art]        Multai   
99975                      [DIYandcrafts, Movies, Books]        Pehowa   
99977                                          [History]    Shertallai   
99987  [Cooking, Businessandentrepreneurship, Outdoor...     Amaravati   

      Country  Age  
9       India   22  
14      India   56  
15      India   41  
21      India   59  
35      India   32  
...       ...  ...  
99936   India   62  
99952   India   48  
99975   India   38  
99977   India   29  
99987   India   55  

[9399 rows x 7 columns]

In [53]:
df['Age'] = df['Age'].astype(str)

In [54]:
df

UserID               Name  Gender  \
9          10   Charles Figueroa  Female   
14         15      Homer Maxwell    Male   
15         16       Frank Holmes  Female   
21         22  Bobby Christensen    Male   
35         36        Erica Dilks  Female   
...       ...                ...     ...   
99936   99937      David Burgess  Female   
99952   99953     Jacquelin Cook    Male   
99975   99976      Katie Almeida    Male   
99977   99978       George Macon    Male   
99987   99988       Shannon Veal  Female   

                                               Interests          City  \
9                                            [Gardening]        Ongole   
14     [Art, Cooking, Carsandautomobiles, Fashion, Hi...        Biaora   
15                                 [Music, Pets, Sports]    Islāmnagar   
21                                        [Nature, Pets]      Rājpīpla   
35                                   [Healthandwellness]  Quthbullapur   
...                                                  ...           ...   
99936                                 [History, Fashion]      Kākināda   
99952                    [Nature, Fashion, Fashion, Art]        Multai   
99975                      [DIYandcrafts, Movies, Books]        Pehowa   
99977                                          [History]    Shertallai   
99987  [Cooking, Businessandentrepreneurship, Outdoor...     Amaravati   

      Country Age  
9       India  22  
14      India  56  
15      India  41  
21      India  59  
35      India  32  
...       ...  ..  
99936   India  62  
99952   India  48  
99975   India  38  
99977   India  29  
99987   India  55  

[9399 rows x 7 columns]

In [55]:
df['Tags'] = df['Gender'] + " "+df['City'] + " " +df['Age'] + " "+ df['Interests'].apply(lambda x: ' '.join(x)) + " "

In [56]:
df

UserID               Name  Gender  \
9          10   Charles Figueroa  Female   
14         15      Homer Maxwell    Male   
15         16       Frank Holmes  Female   
21         22  Bobby Christensen    Male   
35         36        Erica Dilks  Female   
...       ...                ...     ...   
99936   99937      David Burgess  Female   
99952   99953     Jacquelin Cook    Male   
99975   99976      Katie Almeida    Male   
99977   99978       George Macon    Male   
99987   99988       Shannon Veal  Female   

                                               Interests          City  \
9                                            [Gardening]        Ongole   
14     [Art, Cooking, Carsandautomobiles, Fashion, Hi...        Biaora   
15                                 [Music, Pets, Sports]    Islāmnagar   
21                                        [Nature, Pets]      Rājpīpla   
35                                   [Healthandwellness]  Quthbullapur   
...                                                  ...           ...   
99936                                 [History, Fashion]      Kākināda   
99952                    [Nature, Fashion, Fashion, Art]        Multai   
99975                      [DIYandcrafts, Movies, Books]        Pehowa   
99977                                          [History]    Shertallai   
99987  [Cooking, Businessandentrepreneurship, Outdoor...     Amaravati   

      Country Age                                               Tags  
9       India  22                        Female Ongole 22 Gardening   
14      India  56  Male Biaora 56 Art Cooking Carsandautomobiles ...  
15      India  41            Female Islāmnagar 41 Music Pets Sports   
21      India  59                      Male Rājpīpla 59 Nature Pets   
35      India  32          Female Quthbullapur 32 Healthandwellness   
...       ...  ..                                                ...  
99936   India  62                Female Kākināda 62 History Fashion   
99952   India  48         Male Multai 48 Nature Fashion Fashion Art   
99975   India  38          Male Pehowa 38 DIYandcrafts Movies Books   
99977   India  29                        Male Shertallai 29 History   
99987   India  55  Female Amaravati 55 Cooking Businessandentrepr...  

[9399 rows x 8 columns]

In [57]:
final_df = df[['UserID', 'Name', 'Tags']]

In [58]:
final_df.head()

UserID               Name  \
9       10   Charles Figueroa   
14      15      Homer Maxwell   
15      16       Frank Holmes   
21      22  Bobby Christensen   
35      36        Erica Dilks   

                                                 Tags  
9                         Female Ongole 22 Gardening   
14  Male Biaora 56 Art Cooking Carsandautomobiles ...  
15            Female Islāmnagar 41 Music Pets Sports   
21                      Male Rājpīpla 59 Nature Pets   
35          Female Quthbullapur 32 Healthandwellness

In [59]:
final_df

UserID               Name  \
9          10   Charles Figueroa   
14         15      Homer Maxwell   
15         16       Frank Holmes   
21         22  Bobby Christensen   
35         36        Erica Dilks   
...       ...                ...   
99936   99937      David Burgess   
99952   99953     Jacquelin Cook   
99975   99976      Katie Almeida   
99977   99978       George Macon   
99987   99988       Shannon Veal   

                                                    Tags  
9                            Female Ongole 22 Gardening   
14     Male Biaora 56 Art Cooking Carsandautomobiles ...  
15               Female Islāmnagar 41 Music Pets Sports   
21                         Male Rājpīpla 59 Nature Pets   
35             Female Quthbullapur 32 Healthandwellness   
...                                                  ...  
99936                Female Kākināda 62 History Fashion   
99952         Male Multai 48 Nature Fashion Fashion Art   
99975          Male Pehowa 38 DIYandcrafts Movies Books   
99977                        Male Shertallai 29 History   
99987  Female Amaravati 55 Cooking Businessandentrepr...  

[9399 rows x 3 columns]

In [60]:
type(final_df['Tags'])


pandas.core.series.Series

In [61]:
final_df

UserID               Name  \
9          10   Charles Figueroa   
14         15      Homer Maxwell   
15         16       Frank Holmes   
21         22  Bobby Christensen   
35         36        Erica Dilks   
...       ...                ...   
99936   99937      David Burgess   
99952   99953     Jacquelin Cook   
99975   99976      Katie Almeida   
99977   99978       George Macon   
99987   99988       Shannon Veal   

                                                    Tags  
9                            Female Ongole 22 Gardening   
14     Male Biaora 56 Art Cooking Carsandautomobiles ...  
15               Female Islāmnagar 41 Music Pets Sports   
21                         Male Rājpīpla 59 Nature Pets   
35             Female Quthbullapur 32 Healthandwellness   
...                                                  ...  
99936                Female Kākināda 62 History Fashion   
99952         Male Multai 48 Nature Fashion Fashion Art   
99975          Male Pehowa 38 DIYandcrafts Movies Books   
99977                        Male Shertallai 29 History   
99987  Female Amaravati 55 Cooking Businessandentrepr...  

[9399 rows x 3 columns]

In [62]:
final_df

UserID               Name  \
9          10   Charles Figueroa   
14         15      Homer Maxwell   
15         16       Frank Holmes   
21         22  Bobby Christensen   
35         36        Erica Dilks   
...       ...                ...   
99936   99937      David Burgess   
99952   99953     Jacquelin Cook   
99975   99976      Katie Almeida   
99977   99978       George Macon   
99987   99988       Shannon Veal   

                                                    Tags  
9                            Female Ongole 22 Gardening   
14     Male Biaora 56 Art Cooking Carsandautomobiles ...  
15               Female Islāmnagar 41 Music Pets Sports   
21                         Male Rājpīpla 59 Nature Pets   
35             Female Quthbullapur 32 Healthandwellness   
...                                                  ...  
99936                Female Kākināda 62 History Fashion   
99952         Male Multai 48 Nature Fashion Fashion Art   
99975          Male Pehowa 38 DIYandcrafts Movies Books   
99977                        Male Shertallai 29 History   
99987  Female Amaravati 55 Cooking Businessandentrepr...  

[9399 rows x 3 columns]

In [63]:
final_df['Tags']

9                              Female Ongole 22 Gardening 
14       Male Biaora 56 Art Cooking Carsandautomobiles ...
15                 Female Islāmnagar 41 Music Pets Sports 
21                           Male Rājpīpla 59 Nature Pets 
35               Female Quthbullapur 32 Healthandwellness 
                               ...                        
99936                  Female Kākināda 62 History Fashion 
99952           Male Multai 48 Nature Fashion Fashion Art 
99975            Male Pehowa 38 DIYandcrafts Movies Books 
99977                          Male Shertallai 29 History 
99987    Female Amaravati 55 Cooking Businessandentrepr...
Name: Tags, Length: 9399, dtype: object

In [64]:
final_df = final_df.reset_index(drop=True)

In [65]:
final_df

UserID               Name  \
0         10   Charles Figueroa   
1         15      Homer Maxwell   
2         16       Frank Holmes   
3         22  Bobby Christensen   
4         36        Erica Dilks   
...      ...                ...   
9394   99937      David Burgess   
9395   99953     Jacquelin Cook   
9396   99976      Katie Almeida   
9397   99978       George Macon   
9398   99988       Shannon Veal   

                                                   Tags  
0                           Female Ongole 22 Gardening   
1     Male Biaora 56 Art Cooking Carsandautomobiles ...  
2               Female Islāmnagar 41 Music Pets Sports   
3                         Male Rājpīpla 59 Nature Pets   
4             Female Quthbullapur 32 Healthandwellness   
...                                                 ...  
9394                Female Kākināda 62 History Fashion   
9395         Male Multai 48 Nature Fashion Fashion Art   
9396          Male Pehowa 38 DIYandcrafts Movies Books   
9397                        Male Shertallai 29 History   
9398  Female Amaravati 55 Cooking Businessandentrepr...  

[9399 rows x 3 columns]

In [66]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')


In [67]:
cv

CountVectorizer(max_features=5000, stop_words='english')

In [68]:
cv.fit_transform(final_df['Tags']).toarray()

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(9399, 2516))

In [69]:
vectors = cv.fit_transform(final_df['Tags']).toarray()

In [70]:
vectors

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(9399, 2516))

In [71]:
vectors[0]

array([0, 0, 1, ..., 0, 0, 0], shape=(2516,))

In [72]:
len(cv.get_feature_names_out())

2516

In [73]:
from sklearn.metrics.pairwise import cosine_similarity

In [74]:
similarity = cosine_similarity(vectors)

In [75]:
similarity[2]

array([0.20412415, 0.        , 1.        , ..., 0.        , 0.        ,
       0.16666667], shape=(9399,))

In [76]:
"hello"

'hello'

In [77]:
similarity

array([[1.        , 0.        , 0.20412415, ..., 0.        , 0.        ,
        0.20412415],
       [0.        , 1.        , 0.        , ..., 0.14433757, 0.35355339,
        0.14433757],
       [0.20412415, 0.        , 1.        , ..., 0.        , 0.        ,
        0.16666667],
       ...,
       [0.        , 0.14433757, 0.        , ..., 1.        , 0.20412415,
        0.        ],
       [0.        , 0.35355339, 0.        , ..., 0.20412415, 1.        ,
        0.        ],
       [0.20412415, 0.14433757, 0.16666667, ..., 0.        , 0.        ,
        1.        ]], shape=(9399, 9399))

In [78]:
sorted(list(enumerate(similarity[0])), reverse=True, key = lambda x:x[1])[1:6]

[(7623, np.float64(0.75)),
 (3169, np.float64(0.6708203932499369)),
 (3617, np.float64(0.6123724356957946)),
 (2525, np.float64(0.5669467095138407)),
 (4920, np.float64(0.5669467095138407))]

In [79]:
def recommend(profile):
    person_index = final_df[final_df['Name'] == profile].index[0]
    distances = similarity[person_index]
    recc_list = sorted(list(enumerate(distances)), reverse=True, key = lambda x:x[1])[1:6]

    for i in recc_list:
        user_id = int(final_df.iloc[i[0]]['UserID'])
        user_info = final_df[final_df['UserID'] == user_id][['UserID', 'Name', 'Tags']]
        print(user_info)

    return 


In [80]:
recommend("George Macon")

     UserID        Name                           Tags
518    5527  Ellen Hahn  Male Nāgod 29 History Beauty 
      UserID              Name                              Tags
1651   17468  Carolyn Latouche  Male Safīpur 29 History Fitness 
      UserID           Name                                               Tags
2291   23995  Archie Angulo  Male Rājgarh 29 Beauty Fitness History Foodand...
      UserID             Name  \
3723   39531  Eduardo Stewart   

                                                   Tags  
3723  Male Sālūr 29 Carsandautomobiles History Cooki...  
     UserID          Name                                              Tags
512    5464  Brenda Boone  Male Kulti 33 History Healthandwellness History 


In [81]:
final_df.loc[518]

UserID                             5527
Name                         Ellen Hahn
Tags      Male Nāgod 29 History Beauty 
Name: 518, dtype: object